declare module 'typeface-poppins'
declare module 'typeface-nunito'
declare module 'typeface-jetbrains-mono'
declare module 'typeface-montserrat'
declare module 'typeface-dancing-script'
declare module 'typeface-merienda'
declare module 'typeface-inter'
